### ISSUE TITLE
Why was this deprecated?

### ISSUE THREAD

**Issue by arianitu** [Wufe/react-particles-js#193]
Just wondering why this was deprecated in favour of react-tsparticles?

**Comment by wufe** [comment]
In March 2020 the underlying code for the particles movements has been swapped with `tsparticles`, in order to have a common codebase, making this library a de facto React wrapper on top of it.

The `tsparticles` repository have a much bigger community and more frequent fixes/feature implementations.

Since then, frequent misalignments between versions of react/typescript/tsparticles have caused some integration bugs on this library, and I'm currently not actively working on it.

Since all this library does now is to provide a wrap on top of that core engine, I deprecated `react-particles-js` in favor of the official React wrapper that is being maintained alongside `tsparticles`, [react-tsparticles](https://www.npmjs.com/package/react-tsparticles), so the users can get better support.
