### ISSUE TITLE
Multiples Images broken after latest 2.3.0

### ISSUE THREAD

**Issue by wdavidw** [Wufe/react-particles-js#51]
The animation is very slow and images keep flashing. I tried setting the "fps_limit" property without success, any ideas ?

**Comment by Wufe** [comment]
Can you tell me how to reproduce and what's the error encountered?

**Comment by wdavidw** [comment]
I have dig the problem a little further. I was hoping there was maybe clear reason to it. The particle component is used on the [Nikita website](https://nikita.js.org/) build with [Gatsby](https://www.gatsbyjs.org) in a separate [GitHub repo](https://github.com/adaltas/node-nikita-docs). In version 2.2.0, everything is fine. In version 2.3.0, I have two observation:

- It is much slower, not really an issue as I can just raise the "speed" parameter from "1" to "10" to achieve a similar speed.
- Some images are flashing on top of the animation. Note, this is only observed in "develop" mode (`npm run develop`) when react is rendered in the browser and not in "build" mode (`npm run build && npm run serve`) when react is rendered on the server.

The react component is present [here](https://github.com/adaltas/node-nikita-docs/blob/master/src/components/home/Intro.js) and the "render" method is only called once (unless the window is resized by the user)

**Comment by wdavidw** [comment]
I am going to close this issue because I've just done many optimizations to our home page and the flashing issue is no longer present and won't be reproducible with the latest source code on our GitHub repo. Maybe it was me or some cache issue (despite having clean up everything I was aware of in both firefox and chrome).

**Comment by wdavidw** [comment]
I spoke too fast. Still present.

**Comment by wdavidw** [comment]
I just discover that the reported bug is visible when the menu is toggle on the [Nikita homepage](https://nikita.js.org/). Simply press the menu icon on the top left corner of the page to see it in action. The flash are active on Firefox and little less on on Chrome. I've also noticed that the speed of the flash vary depending on the value of `fps_limit`.

**Comment by Wufe** [comment]
I managed to fix some issues above.
Not sure if the flash effect on the icons is still present, but I **completely changed** the way the images are loaded.
The structure was not suited to handle multiple images very well ( to be honest, it was not suited to handle new code at all ).
The version including these changes is `v2.4.0-beta.2` which is available through `npm install react-particles-js@2.4.0-beta.2` ( it is not available through a simple `npm install react-particles-js` ).

With this version I'm trying to start to get rid of the old code which was derived by the original code base.

If you want to, you can help me test the 2.4.0-beta.2 version.

### Issues

+ *FPS Limit Changes the speed of the animation*
+ *Shape type must be able to parse an array*
+ *Embedded Base64 SVG images are not rendered simultaneously*
+ *No data definitions for images shape type*
+ *Actual number of rendered particles equals to number of requested particles multiplied by the number of images*

****
### FPS Limit Changes the speed of the animation

The parameter should be initialized to 999 allowing backward compatibility.

***
### Shape type must be able to parse an array

The function isInArray must do the trick.
Nevertheless, **images** and **image** types cannot work simultaneously.

***
### Embedded Base64 SVG images are not rendered simultaneously

The reason is the images are loaded within the same data structure.
Another structure is required.

***
### No data definitions for images shape type

Must be included.

***
### Actual number of rendered particles equals to number of requested particles multiplied by the number of images

Each loadImg() function call triggers a checkBeforeDraw() which was not ready to accept an array of images instead a single image.
The code which should check whether every image is loaded, was commented without further implementation.

***
## Optimizations & Refactoring

### Issues
+ *No-op while loading images*
+ *Incosistency in type definitions*

***
### **No-op while loading images**
`requestAnimationFrame(undefined)` was coded (but never called) while all images where not loaded instead of using async load, promises or callback.

**Comment by wdavidw** [comment]
Thank you for the feedback @Wufe . You are right, the code structure really wasn't optimal for multiple images, I made it worked but it looks more like a hack.

**Comment by wdavidw** [comment]
Re-opening, I've being try version 2.4.0-beta.3, it now longer work with server side generation, any quick idea ?

**Comment by Wufe** [comment]
I made a few changes to enable SSR.  
I'm not sure this is the right path tho, because this could introduce a breaking change: the Particles object is not defined anymore under the window object.
This means it cannot be used as external import (e.g. `<script src="https://unpkg.com/react-particles-js@2.4.0-beta.10/lib/particles.js"></script>`).  
I may think to provide another output bundle, like `particles.window.js` for this use case.

Anyway, if you want to try the new version and provide some feedback, `npm install react-particles-js@2.4.0-beta.10`.

**Comment by wdavidw** [comment]
Latest beta 10 works perfectly with SSR. Also, I confirm there are no more blinking on the [Nikita website](https://nikita.js.org/). About defining the Particles object under the window object, can't you work around with a condition like `if(typeof windows !== 'undefined')`?
