### ISSUE TITLE
child components not showing

### ISSUE THREAD

**Issue by NoelAnnParisi** [Wufe/react-particles-js#8]
hello! thankfully I found this library, I have two small questions.

1. How do I set the background color(I've tried configuring it in the params object just that doesn't seem to have an effect)
2.How would you suggestI render the rest of my app's components?
- as of now, the particles render to the screen but not anything else. 

Here's what I am working with: 
```
import Main from './components/Main';
import React from 'react';
import ReactDOM from 'react-dom';

import Particle from './container/Particle'

ReactDOM.render(
  <Particle>
    <Main />
  </Particle>,
  document.getElementById('app')
)
```

I've abstracted Partcle into it's own file becasue of it's length

**Comment by NoelAnnParisi** [comment]
Quick Update: I modified my code to look like this: 
``` 
import React from 'react';
import ReactDOM from 'react-dom';

import Particle from './container/Particle'

ReactDOM.render(
  <Particle/>,
  document.getElementById('app')
)
```

and the Particle component looks like this: 

`` import React, {Component} from 'react'
import Particles from 'react-particles-js';
import Main from '../components/Main';

const Particle = () => {
  return (
    <Particles 
      params={{ alll th params}}>
      <Main />
   </Particles>
  )
}
export default Particle 
```

But still no luck

**Comment by Wufe** [comment]
Hi, you can take look at the [demo source](https://github.com/Wufe/react-particles-js/blob/master/demo/index.html) to see how to solve both of your problems:

- The background-color can be set in the element containing the `<Particles />` component; in the example I set the background-color in the body element, but it can be done in the element that contains the component i.e. the `.wrapper` div.

- Currently the component does not support children; you can set however a fixed/absolute/relative position or a float for your particle component, then put other components beside the particle component, and style them to show over the particle component. This is because canvas cannot have children tags.

**Comment by NoelAnnParisi** [comment]
That's all great information!

I did end up looking at the demo's source code and gave it a fixed
position. That code was very helpful and solved the issue 👍🏼

I would have closed the issue earlier but I got lost in coding.

Thank you for the response and tips!

Best,

Noel

**Comment by Wufe** [comment]
You are welcome.
Feel free to open another issue if you have suggestions for improvement

**Comment by NoelAnnParisi** [comment]
Thanks!

Last quick observation: I notice that my site only recognizes my mouse
after having has clicked in the page.

Is there a way to edit that in the params prop?

Best,

Noel

**Comment by NoelAnnParisi** [comment]
I do have onhover enabled.

**Comment by Wufe** [comment]
What browser are you using? In chrome the canvas recognizes the mouse without a click

**Comment by Wufe** [comment]
No comments for 3 months. Closing the issue.
